name: dementia-environment
channels:
  - conda-forge
  - scitools
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - notebook
  - datetime
  - glob
  - itertools
  - mpl_toolkits
  - warnings
  - python>3.6.2
  - ipython-genutils
  - jupyter-client==5.1.0
  - jupyter-console
  - jupyter-core
  - prompt-toolkit
