name: dementia-environment
channels:
  - conda-forge
  - scitools
  - defaults
dependencies:
  - python>3.6.2
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - notebook
  - pip:
    - glob
    - itertools
    - mpl_toolkits
    - datetime
    - warnings
    - ipython-genutils
    - jupyter-client==5.1.0
    - jupyter-console
    - jupyter-core
    - prompt-toolkit
