name: dementia-environment
channels:
  - conda-forge
  - scitools
  - defaults
dependencies:
  - python>3.7.6
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - notebook
  - pip
  - pip:
    - datetime
    - warnings
    - ipython-genutils
    - jupyter-client==5.1.0
    - jupyter-console
    - jupyter-core
